-- MEMBER TABLE
CREATE TABLE MEMBER(
  ID NVARCHAR2(30) NOT NULL 
, PWD NVARCHAR2(30) NOT NULL 
, NICKNAME VARCHAR2(20) NOT NULL 
, EMAIL VARCHAR2(40) NOT NULL 
, ADMIN NUMBER NOT NULL 
, CONSTRAINT MEMBER_PK PRIMARY KEY (ID) ENABLE 
);
COMMENT ON COLUMN MEMBER.ID IS '아이디';
COMMENT ON COLUMN MEMBER.PWD IS '패스워드';
COMMENT ON COLUMN MEMBER.NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ADMIN IS '관리자 여부';



-- STATION TABLE
CREATE TABLE STATION(
  ID NUMBER(2) NOT NULL 
, LANE NVARCHAR2(20) NOT NULL 
, STATION NVARCHAR2(20) NOT NULL 
, CONSTRAINT STATION_PK PRIMARY KEY (ID) ENABLE 
);
COMMENT ON COLUMN STATION.ID IS '역번호';
COMMENT ON COLUMN STATION.LANE IS '노선';
COMMENT ON COLUMN STATION.STATION IS '역이름';



-- BOARD TABLE
CREATE TABLE BOARD 
(
  ID NUMBER(2) NOT NULL 
, NAME NVARCHAR2(20) NOT NULL 
, CONSTRAINT BOARD_PK PRIMARY KEY (ID) ENABLE 
);
COMMENT ON COLUMN BOARD.ID IS '게시판번호';
COMMENT ON COLUMN BOARD.NAME IS '게시판이름';


-- ARTICLE TABLE
CREATE SEQUENCE ARTICLE_SEQ START WITH 1;

CREATE TABLE ARTICLE (
  NO NUMBER(2) DEFAULT ARTICLE_SEQ.nextval NOT NULL 
, TITLE NVARCHAR2(20) NOT NULL 
, CONTENT CLOB NOT NULL 
, POSTDATE DATE NOT NULL 
, HITS NUMBER(3) NOT NULL 
, WRITER NVARCHAR2(30) NOT NULL 
, STATIONID NUMBER(2) NOT NULL 
, BOARDID NUMBER(2) NOT NULL 
, CONSTRAINT ARTICLE_PK PRIMARY KEY (NO) ENABLE 
);

ALTER TABLE ARTICLE
ADD CONSTRAINT ARTICLE_BOARDID_FK FOREIGN KEY (BOARDID) REFERENCES BOARD(ID) ENABLE;

ALTER TABLE ARTICLE
ADD CONSTRAINT ARTICLE_STATIONID_FK FOREIGN KEY(STATIONID) REFERENCES STATION(ID) ENABLE;

ALTER TABLE ARTICLE
ADD CONSTRAINT ARTICLE_WRITER_FK FOREIGN KEY(WRITER) REFERENCES MEMBER(ID) ENABLE;

COMMENT ON COLUMN ARTICLE.NO IS '글번호';
COMMENT ON COLUMN ARTICLE.TITLE IS '제목';
COMMENT ON COLUMN ARTICLE.CONTENT IS '내용';
COMMENT ON COLUMN ARTICLE.POSTDATE IS '작성일';
COMMENT ON COLUMN ARTICLE.HITS IS '조회수';
COMMENT ON COLUMN ARTICLE.WRITER IS '작성자';
COMMENT ON COLUMN ARTICLE.STATIONID IS '역번호';
COMMENT ON COLUMN ARTICLE.BOARDID IS '게시판번호';



-- REPLY TABLE
CREATE SEQUENCE REPLY_SEQ START WITH 1;

CREATE TABLE REPLY (
  NO NUMBER(2) DEFAULT REPLY_SEQ.nextval NOT NULL 
, CONTENT CLOB NOT NULL 
, POSTDATE DATE NOT NULL 
, WRITER NVARCHAR2(30) NOT NULL 
, ARTICLENO NUMBER(2) NOT NULL 
, CONSTRAINT REPLY_PK PRIMARY KEY(NO) ENABLE
);

ALTER TABLE REPLY
ADD CONSTRAINT REPLY_ARTICLENO_FK FOREIGN KEY(ARTICLENO) REFERENCES ARTICLE(NO) ENABLE;

ALTER TABLE REPLY
ADD CONSTRAINT REPLY_WRITER_FK FOREIGN KEY(WRITER) REFERENCES MEMBER(ID) ENABLE;