CREATE SEQUENCE ARTICLE_SEQ START WITH 1;

CREATE TABLE ARTICLE 
(
  NO NUMBER(2) DEFAULT ARTICLE_SEQ.nextval NOT NULL 
, TITLE NVARCHAR2(20) NOT NULL 
, CONTENT CLOB NOT NULL 
, POSTDATE DATE NOT NULL 
, HITS NUMBER(3) NOT NULL 
, WRITER NVARCHAR2(30) NOT NULL 
, STATIONID NUMBER(2) NOT NULL 
, BOARDID NUMBER(2) NOT NULL 
, CONSTRAINT ARTICLE_PK PRIMARY KEY 
  (
    NO 
  )
  ENABLE 
);

ALTER TABLE ARTICLE
ADD CONSTRAINT ARTICLE_BOARDID_FK FOREIGN KEY
(
  BOARDID 
)
REFERENCES BOARD
(
  ID 
)
ENABLE;

ALTER TABLE ARTICLE
ADD CONSTRAINT ARTICLE_STATIONID_FK FOREIGN KEY
(
  STATIONID 
)
REFERENCES STATION
(
  ID 
)
ENABLE;

ALTER TABLE ARTICLE
ADD CONSTRAINT ARTICLE_WRITER_FK FOREIGN KEY
(
  WRITER 
)
REFERENCES MEMBER
(
  ID 
)
ENABLE;

COMMENT ON COLUMN ARTICLE.NO IS '글번호';

COMMENT ON COLUMN ARTICLE.TITLE IS '제목';

COMMENT ON COLUMN ARTICLE.CONTENT IS '내용';

COMMENT ON COLUMN ARTICLE.POSTDATE IS '작성일';

COMMENT ON COLUMN ARTICLE.HITS IS '조회수';

COMMENT ON COLUMN ARTICLE.WRITER IS '작성자';

COMMENT ON COLUMN ARTICLE.STATIONID IS '역번호';

COMMENT ON COLUMN ARTICLE.BOARDID IS '게시판번호';