CREATE TABLE MEMBER 
(
  ID NVARCHAR2(30) NOT NULL 
, PWD NVARCHAR2(30) NOT NULL 
, NICKNAME VARCHAR2(20) NOT NULL 
, EMAIL VARCHAR2(40) NOT NULL 
, ADMIN NUMBER NOT NULL 
, CONSTRAINT MEMBER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN MEMBER.ID IS '아이디';

COMMENT ON COLUMN MEMBER.PWD IS '패스워드';

COMMENT ON COLUMN MEMBER.NICKNAME IS '닉네임';

COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';

COMMENT ON COLUMN MEMBER.ADMIN IS '관리자 여부';