CREATE TABLE STATION 
(
  ID NUMBER(2) NOT NULL 
, LANE NVARCHAR2(20) NOT NULL 
, STATION NVARCHAR2(20) NOT NULL 
, CONSTRAINT STATION_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

COMMENT ON COLUMN STATION.ID IS '역번호';

COMMENT ON COLUMN STATION.LANE IS '노선';

COMMENT ON COLUMN STATION.STATION IS '역이름';