CREATE SEQUENCE REPLY_SEQ START WITH 1;

CREATE TABLE REPLY 
(
  NO NUMBER(2) DEFAULT REPLY_SEQ.nextval NOT NULL 
, CONTENT CLOB NOT NULL 
, POSTDATE DATE NOT NULL 
, WRITER NVARCHAR2(30) NOT NULL 
, ARTICLENO NUMBER(2) NOT NULL 
, CONSTRAINT REPLY_PK PRIMARY KEY 
  (
    NO 
  )
  ENABLE 
);

ALTER TABLE REPLY
ADD CONSTRAINT REPLY_ARTICLENO_FK FOREIGN KEY
(
  ARTICLENO 
)
REFERENCES ARTICLE
(
  NO 
)
ENABLE;

ALTER TABLE REPLY
ADD CONSTRAINT REPLY_WRITER_FK FOREIGN KEY
(
  WRITER 
)
REFERENCES MEMBER
(
  ID 
)
ENABLE;